### PR TITLE
Campaigns

### PR DESCRIPTION
**Pull request by nazar**
Hey @mikelax 

A PR that sets up a basic client page (currently unlinked to navbar) in `/campaigns` and a graphQL schema, resolvers and scope checked in the API.

I was looking at the client folder on Sunday to hook up route redirects depending on login status on the client.

I’m not so keen on the current implementation of auth in the App component, specifically: it has to passed down to all descendants; the Auth class is dealing with too many concerns and there is a mixture of class and instance methods. I fear the Auth class will only get more convoluted.

Redux is often uses to address this type of concern where the auth will be defined in a global state and any component can subscribe to it without having the `auth` reference passed through component hierarchies. Auth0 has an example implementation (although it is slightly dated) here: https://auth0.com/blog/secure-your-react-and-redux-app-with-jwt-authentication/

I’m not going to tackle this in the `campaigns` PR (I’ll only implement the scope checks there) but will have a look at `auth`, Redux and a grid layout for the client in subsequent PRs.

### CODE REVIEW

**Comment by mikelax** [comment]
@nazar  Looking pretty good. 
One issue I found, after the insert completes on the `create` page, the user is redirected back to the list page but the newly created campaign is not displayed. either browser page refresh or navigate to a new page and then back button *will* display the new data.

**Comment by nazar** [comment]
Hey @mikelax 

>but the newly created campaign is not displayed

Yep - I haven't addressed that yet. It's to do with setting up the apollo-client's caching layer for it to be able to identify objects in the cache. The udemy course covers this but I haven't implemented it yet.

**Comment by nazar** [comment]
Hey @mikelax - any chance of this PR hitting master tonight? I'd like to start a new branch based on this tomorrow morning for the next phase. 

I'm thinking of starting on a basic `campain_messages` to play with a message editor, how messages look in the UI, and setting up a push-notification system using graphQL subscriptions.

**Comment by mikelax** [comment]
@nazar  doing final quick test, should merge in next 10-15 minutes

**Comment by mikelax** [comment]
@nazar  everything looks good. 
one tiny change that we can adjust later, if you are logged out, or if your jwt has expired the page is not redirecting to the login page, instead just showing the error page from a 401.

**Pull request merged**
